apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: delivery-unified-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /orders
        pathType: Prefix
        backend:
          service:
            name: order-svc
            port:
              number: 5001
      - path: /pilots
        pathType: Prefix
        backend:
          service:
            name: pilot-svc
            port:
              number: 5002
